language: node_js

env:
  global:
    - REPO: maxwoj/resume
    - DOCKER_USERNAME: maxwoj
    - secure: "HYr+3GHtOXYmfzuuH75FJIWCt+iqhVs35UcLEKxsfkDdem+hw6V48P2+X/l7jweaE4iaZ87llJ/3+ftUtjzez6kh001HbRfOtRYI6L25na4EPgzgApn4aLAQuWq+5c6Nid8ZYRI1wTc+vukuWt7GmfCxKhV0GrB5hLxBFI+mpHhNOwrBTOexWw0Zh1OdqFS8RYu3+GAgPgNDhKh7P+WnphmyzV1GyXPa4WM947CGksivIb4NXxaQ13/jByvqrrLKcqw2BuloaWy7RaYSsmOcQdHF7Ah5RTC+3RI4OcrhPfC91fbtqwGgKJ1zdqibv+mILpu/gik/4vfuSqHAhjwx5OnY6s6h7Pq5T5JxNXjh+LwejQ5D1R5jpQxejx3yukybSakmITRW4L7C0VI4qcw8dN1cEZ9rL+9bSOd8Diur79jlj9rXb8xCBVtMTgvC+Dx7+GNLP0m8rmdnXFS12IyBL+wVbGlJUeVCg6hL8uPF4Ut91nYQUKyKcPwEQs4I29GGZ1jpSQEaG9cJ3lybdCMdYjlowaw3nmu2CMthJ3gh5gns3pZydrv2YZtpOipyuKKn4Ayrmgq0xQEKQn8uB9JmBTcs69D9OBmIU5IerWfTHBCGc1+FJUmM+AumVX4cb/gRDT8+9rlD8nfTDNRpIW/dxlTRt15h6KqgB2bE6Sm1AKk="
    - secure: "h/Npxv4y5KAax1nmva2YZUTv0ZgTr5EO3rLs6hVZUed+ufPb5AVBHkKTzsk2tZ2hWtztTVjr21tcg64AypSdM44nRCd+C6aQTUMtiDpXEHgQUESlaLftaMixQibAVK/Gjvn4Ph3NSOWSX8jVgVxC7IJ2Y7HWJHXGHz9NqDaLXn11tI16MWxo/9ulq4F1/vE2epnme2HtVk39OostenrtbjGvZWRW1EEOptNGUOWfSbyz5E6p1uq1kram8wrtwY4U2aiQHKY5eimvkwqYwpr10sfCfqIyNxk9uCFdtdtI1qCJnpWZJ9NrUqaKIAZyTI3Kp+msRJuwkuqohYoT7nTzescO9bcEzbFkcngLQTKUdMyL6nIMMmO2k3PkrfwU78ieGRWyd+JKdkNJXIhywbeU+IT/0Hea2ti8ZGW/mIysSJO886JJ90u7A9sXyedZRLezVyu3c7lOjpzItY9tNtMpRbvMzWGEhsawSOvOTPVIUI2GOS1enL9bcwJ+PH9nTD75gTgUB2EUjYzPcfzqN2YCjU5cdhxV9cZMHkIFr8j4kPRXtr5eo9Td82SHzhQJKJ7HbBKas/+4F14SZtagDNV+i0NK6VaWTOXzXPjGkhZCdrouxmHyVlYTj45B4fpbcphSaWGjxhYCLe2GyaxJO5Y9XaUoy8e7TOMKC5nh0wQuvco="

services:
  - docker

before_script:
  - npm install -g grunt
  - npm run build

after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -t $REPO:$TRAVIS_COMMIT .
  - docker tag $REPO:$TRAVIS_COMMIT $REPO:$TAG
  - docker push $REPO

deploy:
  provider: pages
  local_dir: dist
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
